version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: trainer_container
    environment:
      MYSQL_DATABASE: botdatabase
      MYSQL_USER: bot
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data: